### ISSUE TITLE
Add more font pairs

### ISSUE THREAD

**Issue by itsvvishnu** [itsvvishnu/Font-Pair#1]
Add more font pairs in the js file

**Comment by madmaxWMFU** [comment]
Are there any specific styles or random ones to add?

**Comment by itsvvishnu** [comment]
> Are there any specific styles or random ones to add?

Hi,there are no styles to add as of now... you can add two google fonts that mix well together in the fonts.js file if you are interested. thanks

**Comment by madmaxWMFU** [comment]
Ok, i will glad to help you
