### ISSUE TITLE
Select drop down color and contrast fix

### ISSUE THREAD

**Issue by itsvvishnu** [itsvvishnu/Font-Pair#5]
The font pair list title in the dropdown menu are not readable now...change the color or background appropriately

**Comment by GoodGuyGregory** [comment]
@itsvvishnu would it be possible for me to tackle this?

**Comment by bensbits91** [comment]
@itsvvishnu can I submit a PR too?

**Comment by bensbits91** [comment]
@itsvvishnu [I submitted a PR](https://github.com/itsvvishnu/Font-Pair/pull/14). I hope that's OK. Let me know if you have any feedback or questions. Thanks!
